-- ============================================================================
-- 001_schema.sql — LA LegPro PostgreSQL schema (Migration M1)
--
-- Target: PostgreSQL 16 + pgvector (docker image pgvector/pgvector:pg16).
-- Consolidates three SQLite databases and one ChromaDB store:
--   data/legal_metadata.db  -> public schema (regulations, kg_*, metrics, ...)
--   data/users.db           -> public schema (users, chat_*, compliance_*, ...)
--   data/ojk_metadata.db    -> scraper schema (scraper.regulations)
--   data/chroma_db/ + chunks_fts (FTS5) -> public.chunks (single unified table)
--
-- Design notes:
--   * Schemas mirror the LIVE SQLite tables (dumped 2026-09-25), not the
--     stale CREATE TABLE IF NOT EXISTS statements in api/services/db_service.py
--     (e.g. regulations.id is INTEGER identity, klasifikasi DEFAULT 'Publik').
--   * SQLite TEXT timestamps ('YYYY-MM-DD HH:MM:SS', UTC) become TIMESTAMPTZ;
--     the M2 migration script parses and validates every value.
--   * chunks.doc_id is TEXT because the legacy FTS5 doc_id column holds a mix
--     of integers and strings; joins to regulations use regulations.id::text.
--   * chunks replaces BOTH the Chroma collection 'ojk_regulations' (dense,
--     384-d all-MiniLM-L6-v2, cosine) and SQLite chunks_fts (sparse FTS5).
--     Chroma metadata keys map 1:1 to columns; 'reg_id' metadata maps to
--     doc_id. to_tsvector('simple', ...) matches FTS5 unicode61 behavior
--     (no stemming); the sparse query builder OR-joins words as before.
--   * The empty legacy Chroma collections ('legal_docs' in chroma_db,
--     'regulations' in data/chromadb) are intentionally NOT migrated.
--   * Everything is idempotent (IF NOT EXISTS / ON CONFLICT DO NOTHING) so
--     this file can be re-run safely; it is also mounted into
--     /docker-entrypoint-initdb.d and auto-applied on first volume init.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS scraper;

-- ────────────────────────────────────────────────────────────────────────────
-- From legal_metadata.db
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS regulations (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain       TEXT,
    judul        TEXT,
    nomor        TEXT,
    jenis        TEXT,
    sektor       TEXT,
    status       TEXT,
    detail_url   TEXT UNIQUE,
    download_url TEXT,
    local_path   TEXT,
    klasifikasi  TEXT DEFAULT 'Publik'
);

CREATE TABLE IF NOT EXISTS access_grants (
    id         TEXT PRIMARY KEY,
    doc_id     TEXT,
    granted_by TEXT,
    granted_to TEXT,
    reason     TEXT,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_access_grants_granted_to ON access_grants (granted_to);

CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp   TIMESTAMPTZ DEFAULT now(),
    user_id     TEXT,
    action_type TEXT,
    resource_id TEXT,
    details     TEXT
);

CREATE TABLE IF NOT EXISTS kg_nodes (
    id         TEXT PRIMARY KEY,
    label      TEXT NOT NULL,
    type       TEXT NOT NULL,
    doc_id     TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kg_edges (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id  TEXT NOT NULL,
    target_id  TEXT NOT NULL,
    relation   TEXT NOT NULL,
    doc_id     TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_kg_edges_source ON kg_edges (source_id);
CREATE INDEX IF NOT EXISTS idx_kg_edges_target ON kg_edges (target_id);

CREATE TABLE IF NOT EXISTS kg_exclusions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name TEXT UNIQUE NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kg_rebuild_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time    TIMESTAMPTZ,
    end_time      TIMESTAMPTZ,
    duration_s    INTEGER,
    nodes_changed INTEGER,
    edges_changed INTEGER,
    status        TEXT
);

-- metadata_db_mb / users_db_mb keep their names for FE contract parity;
-- after the cutover the metrics loop (M3) fills them with PG relation sizes.
CREATE TABLE IF NOT EXISTS system_metrics (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp      TIMESTAMPTZ DEFAULT now(),
    cpu            DOUBLE PRECISION,
    ram            DOUBLE PRECISION,
    disk           DOUBLE PRECISION,
    metadata_db_mb DOUBLE PRECISION,
    users_db_mb    DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS llm_metrics (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint      TEXT NOT NULL,
    tokens_used   INTEGER,
    latency_ms    INTEGER,
    cost_estimate DOUBLE PRECISION,
    timestamp     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS document_taxonomy (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT UNIQUE NOT NULL,
    parent_id  INTEGER,
    is_active  BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Unified chunk store: replaces Chroma 'ojk_regulations' AND SQLite chunks_fts.
CREATE TABLE IF NOT EXISTS chunks (
    id             TEXT PRIMARY KEY,   -- Chroma/FTS chunk id (32-hex or ingest-generated)
    doc_id         TEXT,               -- regulations.id as text; NULL for legacy unstructured rows
    text           TEXT NOT NULL,
    window_context TEXT,
    domain         TEXT,
    jenis          TEXT,
    judul          TEXT,
    nomor          TEXT,
    sektor         TEXT,
    status         TEXT,
    filename       TEXT,
    doc_category   TEXT,
    visibility     TEXT,
    user_id        TEXT,
    embedding      vector(384),        -- all-MiniLM-L6-v2, cosine; NULL for sparse-only rows
    content_tsv    tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(text, ''))) STORED
);
-- HNSW build over ~55k rows takes ~1 min; cosine ops match Chroma 'hnsw:space: cosine'.
CREATE INDEX IF NOT EXISTS idx_chunks_embedding ON chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_chunks_tsv       ON chunks USING gin (content_tsv);
CREATE INDEX IF NOT EXISTS idx_chunks_doc_id    ON chunks (doc_id);
CREATE INDEX IF NOT EXISTS idx_chunks_filters   ON chunks (doc_category, visibility, user_id);

-- ────────────────────────────────────────────────────────────────────────────
-- From users.db
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    username      TEXT UNIQUE,
    password_hash TEXT,
    email         TEXT,
    role          TEXT DEFAULT 'pengguna',
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_sessions (
    id         TEXT PRIMARY KEY,
    user_id    TEXT,
    title      TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   TEXT,
    role         TEXT,
    content      TEXT,
    sources_json TEXT,
    created_at   TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages (session_id);

CREATE TABLE IF NOT EXISTS compliance_history (
    id              TEXT PRIMARY KEY,
    user_id         TEXT,
    filename        TEXT,
    results_json    TEXT,
    company_name    TEXT,
    expiration_date DATE,
    created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_compliance_history_user ON compliance_history (user_id);

CREATE TABLE IF NOT EXISTS document_templates (
    id               TEXT PRIMARY KEY,
    title            TEXT,
    description      TEXT,
    content_template TEXT,
    category         TEXT,
    created_at       TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS active_sessions (
    user_id   TEXT PRIMARY KEY,
    username  TEXT,
    role      TEXT,
    last_seen TIMESTAMPTZ DEFAULT now(),
    ip_address TEXT
);

-- ────────────────────────────────────────────────────────────────────────────
-- From ojk_metadata.db (separate schema: table name collides with public.regulations)
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS scraper.regulations (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul        TEXT,
    nomor        TEXT,
    jenis        TEXT,
    sektor       TEXT,
    status       TEXT,
    detail_url   TEXT UNIQUE,
    download_url TEXT,
    local_path   TEXT
);

-- ────────────────────────────────────────────────────────────────────────────
-- Seeds (idempotent; mirror the Python seeding in db_service.init_main_db
-- and auth.init_db, which will be retired in M3)
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO document_taxonomy (name) VALUES
    ('Peraturan Pemerintah'),
    ('Undang-Undang'),
    ('Peraturan OJK'),
    ('Surat Edaran OJK'),
    ('Dokumen Internal'),
    ('Peraturan Menteri'),
    ('Regulasi Custom')
ON CONFLICT (name) DO NOTHING;

INSERT INTO document_templates (id, title, description, content_template, category) VALUES
    (
        'tpl_pks_01',
        'Perjanjian Kerja Sama (PKS) Standar',
        'Template PKS standar untuk kerja sama B2B umum dengan penyedia layanan teknologi.',
        $tpl$# PERJANJIAN KERJA SAMA

Pada hari ini, dibuat kesepakatan antara:
1. PIHAK PERTAMA: [Nama Perusahaan 1]
2. PIHAK KEDUA: [Nama Perusahaan 2]

## PASAL 1 - RUANG LINGKUP
Kerja sama ini mencakup [Deskripsi Layanan].

## PASAL 2 - JANGKA WAKTU
Perjanjian ini berlaku selama [Durasi Bulan/Tahun].$tpl$,
        'PKS'
    ),
    (
        'tpl_nda_01',
        'Non-Disclosure Agreement (NDA)',
        'Template perjanjian kerahasiaan dua arah untuk diskusi awal komersial.',
        $tpl$# NON-DISCLOSURE AGREEMENT

Perjanjian kerahasiaan ini ditandatangani oleh:
1. PIHAK PENGUNGKAP: [Nama Pengungkap]
2. PIHAK PENERIMA: [Nama Penerima]

## PASAL 1 - INFORMASI RAHASIA
Informasi yang dilindungi adalah [Jenis Informasi Rahasia].$tpl$,
        'NDA'
    )
ON CONFLICT (id) DO NOTHING;
